title: "Arch Linux User"
description: "Use this portfolio template to tell the world that you use Arch Linux."
encoding: utf-8
enable_dark_theme: true

footer: "If you're not using Arch Linux, this is your sign to check it out!"

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]
